spring:
  datasource:
    name: test
    url: jdbc:mysql://212.64.100.141:3306/boot-security
    username: root
    password: Aa000000
    # druid 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    
  freemarker:
    cache: false
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates
    check-template-location: false
  # 设置静态文件路径，js,css等
mybatis:
  configuration:
    map-underscore-to-camel-case: true

