spring:
  datasource:
    name: test
    url: jdbc:mysql://212.64.100.141:3306/boot-security
    username: root
    password: Aa000000
    # druid 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 配置freemarker

      #指明mapper文件位置
   # mybatis:
      #config-location: classpath:mybatis/mybatis-config.xml  #指定全局配置文件的位置
      #mapper-locations: classpath:mybatis/mapper/*.xml


mybatis:
  configuration:
    map-underscore-to-camel-case: true

